services:
#  postgres:
#    image: postgres:latest
#    container_name: keycloak_postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: kc_user
#      POSTGRES_PASSWORD: kc_pass
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:26.3.2
#    container_name: keycloak
#    restart: unless-stopped
#    command: start-dev
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
#      KC_DB_USERNAME: kc_user
#      KC_DB_PASSWORD: kc_pass
#      KC_HTTP_PORT: 8080
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    restart: always
#    command: [ "redis-server", "--requirepass", "password" ]

#volumes:
#  postgres_data:
#  redis_data:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8002:8080"
    depends_on:
      - db