services:
  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: always
    networks:
      - mfa-net
    environment:
      SPRING_PROFILES_ACTIVE: prod

      # OAUTH2 / SECURITY
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.dara-it.site/realms/mfa
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://keycloak.dara-it.site/realms/mfa/protocol/openid-connect/certs

      # KEYCLOAK CONFIG
      KEYCLOAK_SERVER_URL: https://keycloak.dara-it.site/
      KEYCLOAK_REALM: mfa
      KEYCLOAK_CLIENT_ID: mfa-client
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_TOKEN_ENDPOINT: https://keycloak.dara-it.site/realms/mfa/protocol/openid-connect/token
      KEYCLOAK_END_SESSION_ENDPOINT: https://keycloak.dara-it.site/realms/mfa/protocol/openid-connect/logout

      # MAIL CONFIG
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      # REDIS CONFIG
      SPRING_DATA_REDIS_HOST: 35.198.244.32
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}

      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://localhost:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: "5"
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: "10"
      EUREKA_INSTANCE_INSTANCE_ID: "${SPRING_APPLICATION_NAME}:${SERVER_PORT}"

networks:
  mfa-net:
    external: true