spring:
  application:
    name: authentication

  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.dara-it.site/realms/mfa
          jwk-set-uri: https://keycloak.dara-it.site/realms/mfa/protocol/openid-connect/certs

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: 35.198.244.32
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}

keycloak:
  server-url: https://keycloak.dara-it.site/
  realm: mfa
  client-id: mfa-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  token-endpoint: https://keycloak.dara-it.site/realms/mfa/protocol/openid-connect/token
  end-session-endpoint: https://keycloak.dara-it.site/realms/mfa/protocol/openid-connect/logout

springdoc:
  swagger-ui:
    oauth:
      client-id: mfa-client
      client-secret: ${KEYCLOAK_CLIENT_SECRET}

#server:
#  port: 8081


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
#    instance-id: "${spring.application.name}:${server.port}"